name: "Sync AWS"

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 2 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Login to SIGHUP Registry
      uses: docker/login-action@v1
      with:
        registry: reg.sighup.io
        username: ${{ secrets.SIGHUP_REGISTRY_USERNAME }}
        password: ${{ secrets.SIGHUP_REGISTRY_PASSWORD }}
    - name: Login to SIGHUP new Registry
      uses: docker/login-action@v1
      with:
        registry: registry.sighup.io
        username: ${{ secrets.SIGHUP_NEW_REGISTRY_USERNAME }}
        password: ${{ secrets.SIGHUP_NEW_REGISTRY_PASSWORD }}
    - name: Install yq
      run: |
        sudo apt-get update && sudo apt-get install -yqq wget skopeo
        sudo wget -q https://github.com/mikefarah/yq/releases/download/v4.19.1/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq
    - name: Iterate
      run: |
        ./single_sync.sh modules/aws/images.yml false
